language: node_js
node_js:
  - "12"
dist: trusty
sudo: required

cache:
  directories:
    - ./node_modules

before_install:
  - npm update

install:
  - npm install

script:
  - npm test
  - ng build --prod --base-href https://matjanko.github.io/kalkulatory-budowlane/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/kalkulatory-budowlane
  on:
    branch: master
